<?
	$LANZA_MV='/cloudpyme/.connect/shuttle.sh';
	$KILL_MV='/cloudpyme/.connect/killbill.sh';
	$GET_JOBS='/cloudpyme/.connect/get_jobs_list.pl';

	$RUN_MV_DIR='/cloudpyme/.db/.run';
	$DEAD_MV_DIR='/cloudpyme/.db/.dead';

	$templates['single_1P_2G'] = array ('proc' => 1, 'mem' => 2);
	$templates['single_2P_4G'] = array ('proc' => 2, 'mem' => 4);
	$templates['single_4P_4G'] = array ('proc' => 4, 'mem' => 4);
?>
