
<!-- INICIO FOOTER -->
<div id="footer">
     <div align="center">
          <img src="./../iconos/logos.png" usemap="#map1" alt="Participantes">
          <map name="map1">
          <area target="_new" href="http://www.poctep.eu/" alt="POCTEP" title="POCTEP" shape="rect" coords="0,0,100,93">
          <area target="_new" href="http://www.aimen.es/" alt="AIMEN" title="AIMEN" shape="rect" coords="101,0,245,93">
          <area target="_new" href="http://www.aimmap.pt/" alt="AIMMAP" title="AIMMAP" shape="rect" coords="246,0,425,93">
          <area target="_new" href="http://www.catim.pt/" alt="CATIM" title="CATIM" shape="rect" coords="426,0,550,93">
          <area target="_new" href="http://www.cesga.es/" alt="CESGA" title="CESGA" shape="rect" coords="551,0,700,93">
          <area target="_new" href="http://europa.eu/" alt="FEDER" title="FEDER" shape="rect" coords="701,0,947,93">
           </map>
     </div>
</div> 
<!-- FIN FOOTER -->


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<!-- Bootstrap: Latest compiled and minified JavaScript -->
<script src="http://portal.cloudpyme.eu/js/bootstrap.min.js"></script>

