#!/bin/bash

#################
### FUNCTIONS ###
#################
function print_help {
	echo 'hadoop-iptables'
	echo -e "\t"'hadoop-iptables -h'
	echo -e "\t\t"'Shows this help'
	echo -e "\t"'hadoop-iptables IP'
	echo -e "\t\t"'Adds the given IP to iptables'
	echo -e "\t\t"'For instance: hadoop-iptables 127.0.0.1'
	echo
}


###################
### EXIT VALUES ###
###################
# 0 - Success
# 1 - Insufficient parameters
# 2 - Too much parameters
# 3 - Help requested



### PARSE CMD ###
if [ $# -lt 1 ]; then
	echo 'Insufficient parameters'
	print_help
	exit 1
fi

if [ $# -gt 1 ]; then
	echo 'Too much parameters '
	print_help
	exit 2
fi

if [ $1 == '-h' ] || [ $1 == '--help' ]; then
	print_help
	exit 3;
fi;


### ADD TO IPTABLES ###
num_input_rules=`iptables -S INPUT | wc -l`
num_input_rules=`echo $num_input_rules - 1 | bc`

j=1

for i in $(seq 1 $num_input_rules); do
	if [ $(iptables -S INPUT $j | awk '{print substr($4,0,index($4,"/")-1)}') == $1 ]; then
		iptables -D INPUT $j
	else
		j=`echo $j ' + 1 ' | bc`
	fi
done

iptables -I INPUT 1 -s $1 -j ACCEPT

exit 0
