#!/bin/bash

#################
### FUNCTIONS ###
#################
function print_help {
	echo 'iptables-add'
	echo -e "\t"'hadoop-iptables -h'
	echo -e "\t\t"'Shows this help'
	echo -e "\t"'iptables-add IP'
	echo -e "\t\t"'Adds the given IP to iptables'
	echo -e "\t\t"'For instance: hadoop-iptables 127.0.0.1'
	echo
}


###################
### EXIT VALUES ###
###################
# 0 - Success
# 1 - Insufficient parameters
# 2 - Too much parameters
# 3 - Help requested



### PARSE CMD ###
IP=$1

if [ $# -ne 1 ]; then
	echo 'Bad number of parameters'
	print_help
	exit 1
fi

if [ $1 == '-h' ] || [ $1 == '--help' ]; then
	print_help
	exit 3;
fi;

ocurrences=`iptables -L -n --line-numbers | grep $IP | wc -c`

if [ $ocurrences -lt 1 ]; then
	iptables -I INPUT 1 -s $IP -j ACCEPT
fi

