#!/bin/bash
# vim:tabstop=2:autoindent:expandtab:shiftwidth=2
#
# Author:  Javier Cacheiro Lopez (jlopez@cesga.es)
# Purpose: Get the status of a Hadoop cluster
# Usage:   $0 --option
# Return:  0 if success, 1 if error
#
# Changelog
#   11-10-2013 JLC
#     First version

# Hadoop-on-demand root directory
HADOOP_ROOT=$HOME/.hadoop-on-demand

# Load config if available (overwrites previous default values)
if [[ -r $HADOOP_ROOT/config ]]; then
  . $HADOOP_ROOT/config
fi



cd $HADOOP_ROOT

MASTER=`head -n1 node.list`

ssh hadoop@$MASTER '
echo "==> Hadoop cluster status"
hadoop dfsadmin -report | grep "Datanodes available"
echo -ne "Tasktrackers available "
hadoop job -list-active-trackers|wc -l
echo "===> HDFS"
hadoop dfsadmin -report
echo "===> Task trackers"
hadoop job -list-active-trackers
'
